from __future__ import annotations

import pandas as pd


BACKLOG_COLUMNS = [
    "priority",
    "type",
    "need",
    "demand_score",
    "comments",
    "likes",
    "recommended_action",
    "rationale",
]


def backlog_to_csv(backlog: list[dict]) -> bytes:
    frame = pd.DataFrame(backlog)

    if frame.empty:
        frame = pd.DataFrame(columns=BACKLOG_COLUMNS)
    else:
        for column in BACKLOG_COLUMNS:
            if column not in frame.columns:
                frame[column] = ""
        frame = frame[BACKLOG_COLUMNS]

    return frame.to_csv(index=False).encode("utf-8")


def backlog_to_markdown(backlog: list[dict]) -> str:
    if not backlog:
        return "# Creator Backlog\n\nNo audience needs were found.\n"

    priority_order = {"P0": 0, "P1": 1, "P2": 2, "P3": 3}

    items = sorted(
        backlog,
        key=lambda item: (
            priority_order.get(item.get("priority", "P3"), 9),
            -int(item.get("demand_score", 0)),
        ),
    )

    lines = [
        "# Creator Backlog",
        "",
        "> Generated by CommentOps from recurring audience needs.",
        "",
    ]

    current_priority = None

    for item in items:
        priority = item.get("priority", "P3")
        if priority != current_priority:
            current_priority = priority
            lines.extend([f"## {priority}", ""])

        lines.extend(
            [
                f"### {item.get('need', 'Audience need')}",
                f"- **Type:** {item.get('type', 'Community')}",
                f"- **Demand:** {item.get('demand_score', 0)}/100",
                f"- **Evidence:** {item.get('comments', 0)} comments · {item.get('likes', 0)} combined likes",
                f"- **Recommended action:** {item.get('recommended_action', '')}",
                f"- **Why:** {item.get('rationale', '')}",
                "",
            ]
        )

    return "\n".join(lines).rstrip() + "\n"
